### ISSUE TITLE
Preserve list ordering with multiple patterns

### ISSUE THREAD

**Issue by wdavidw** [sindresorhus/multimatch#14]
Considering: `multimatch(['a/a1', 'b/b', 'a/a2', 'c/c'], ['a/**', 'b/**'])`
I would expect `[ 'a/a1', 'b/b', 'a/a2']`
Instead of `[ 'a/a1', 'a/a2', 'b/b' ]`

If ordering is considered important, it could be offered as an option.

Here's a quick alternative i wrote in coffee. This functionnality is mandatory in my code. I could send you a pull request in js if you are interested, otherwise feel free to discard.

``` coffee
multimatch = (list, patterns, options={}) ->
  list = [list] unless Array.isArray list
  patterns = [patterns] unless Array.isArray patterns
  for el in list
    continue unless patterns.some (pattern) ->
      minimatch el, pattern, options
    el
```

**Comment by sindresorhus** [comment]
Yeah, I don't see why not. A good PR with tests would be accepted :)

*Use a `for` loop rather than `[].forEach` for best perf.*

**Comment by wdavidw** [comment]
Doing so will break [current tests](https://github.com/sindresorhus/multimatch/blob/master/test.js#L22-L26):

`expect(mm(['foo', 'bar', 'baz'], ['*z', 'f*'])).to.eql(['baz', 'foo']);`

Will become:

`expect(mm(['foo', 'bar', 'baz'], ['*z', 'f*'])).to.eql(['foo', 'baz']);`

Do you validate?

**Comment by sindresorhus** [comment]
:+1:
