### ISSUE TITLE
Definitely Typed multimatch definition

### ISSUE THREAD

**Issue by nigurr** [sindresorhus/multimatch#18]
is there any definitely typed multi-match definition that's available for typings?

**Comment by sindresorhus** [comment]
Not that I know of. Not interested in having that here, but can be added to https://github.com/DefinitelyTyped/DefinitelyTyped if needed.

**Comment by SamVerschueren** [comment]
Nope

```
$ typings search multimatch
No results found for search
```

You can always create them and add them to `DefinitelyTyped`. Would be happy to thumbs up the Pr.
