### ISSUE TITLE
0.3.0 uses deprecated minimatch

### ISSUE THREAD

**Issue by misterbrownlee** [sindresorhus/multimatch#20]
An update is needed to get rid of deprecation warnings on install where minimatch is a dependency.

**Comment by misterbrownlee** [comment]
Funny, because master is updated, but multimatch hasn't been released for a long time.  I'm sure there is a story as to why.  Just trying to clean up all the warnings in all the libs I'm using.  I am also trying to contribute patches where I can, so let me know if I can help?

Thanks - Aaron

**Comment by sindresorhus** [comment]
```
$ npm info multimatch dependencies.minimatch
^3.0.0
```

**Comment by misterbrownlee** [comment]
Yeah... it was weird I was getting that deprecation warning.  Sorry about the noise.
