### ISSUE TITLE
Problem matching paths with `./` or `../`

### ISSUE THREAD

**Issue by PopGoesTheWza** [sindresorhus/multimatch#29]
Given the following, I would expect every paths to match.

```js
console.log(
  'test1',
  multimatch(
    ['.z.js', 'a.js', 'a/b.js', 'a/b/c.js', './a.js', 'a/./b.js', 'a/../b.js', '../a/b.js'],
    ['**/*.js'],
    { dot: true },
  ));
```

But the result is

```js
test1 [ '.z.js', 'a.js', 'a/b.js', 'a/b/c.js' ]
```

What am I doing wrong? Have I overlooked something?

Thanks in advance.

**Comment by sindresorhus** [comment]
This is a known issue with the underlying module `minimatch`: https://github.com/isaacs/minimatch/issues/30

**Comment by PopGoesTheWza** [comment]
Thanks
